# Generated by Django 6.1.1 on 2026-09-16 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'CPO -> EMSP (Received)'), ('OUT', 'EMSP -> CPO (Dispatched)')], max_length=4)),
                ('module', models.CharField(default='general', max_length=32)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChargeDetailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdr_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('start_date_time', models.CharField(blank=True, max_length=64)),
                ('end_date_time', models.CharField(blank=True, max_length=64)),
                ('total_energy', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('country_code', models.CharField(default='IN', max_length=2)),
                ('party_id', models.CharField(default='VYT', max_length=3)),
                ('start_date_time', models.CharField(blank=True, max_length=64)),
                ('end_date_time', models.CharField(blank=True, max_length=64)),
                ('kwh', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('status', models.CharField(default='ACTIVE', max_length=32)),
                ('raw_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('command_type', models.CharField(default='START_SESSION', help_text='START_SESSION or STOP_SESSION', max_length=32)),
                ('result', models.CharField(db_index=True, help_text='ACCEPTED, REJECTED, EVSE_INOPERATIVE, FAILED, etc.', max_length=32)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpo_url', models.CharField(default='https://test.vidyutyatraa.co.in', help_text='Live VidyutYatraa CPO Base URL', max_length=255)),
                ('public_base_url', models.CharField(blank=True, default='', help_text='External routable base URL for callbacks (e.g. http://13.232.241.179:8000)', max_length=255)),
                ('bootstrap_token', models.CharField(blank=True, default='', help_text='Token A (Bootstrap handshake token)', max_length=128)),
                ('token_b', models.CharField(default='9e30083e464bec1ddee8e08e5342095d4ea9e1f4a13ba137', help_text='Token B (EMSP uses this to call CPO)', max_length=128)),
                ('token_c', models.CharField(default='emsp-callback-token-secret', help_text='Token C (CPO uses this when calling EMSP)', max_length=128)),
                ('party_id', models.CharField(default='ION', help_text='EMSP Party ID (e.g. ION, SAV, HUB)', max_length=3)),
                ('country_code', models.CharField(default='IN', help_text='EMSP Country Code', max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
