# Generated by Django 6.1.1 on 2026-09-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpi_emsp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulatorconfig',
            name='bootstrap_token',
        ),
        migrations.AddField(
            model_name='simulatorconfig',
            name='token_a',
            field=models.CharField(default='REPLACE_WITH_YOUR_BOOTSTRAP_TOKEN', help_text='Token A (Bootstrap handshake token)', max_length=128),
        ),
    ]
